trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.9.0'

- script: |
    npm init -y
    npm install express
    npm test
  displayName: 'Install and test'

- script: |
    node node.js
  displayName: 'Run Node.js application'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifacts'
    ArtifactName: 'drop'
    publishLocation: 'Container'