trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.9.0'

- script: |
    npm install mocha
    npm install express
  displayName: 'Install dependencies'

- script: |
    mocha
  displayName: 'Run Mocha tests'

- script: |
    node node.js
  displayName: 'Run Node.js application'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifacts'
    ArtifactName: 'drop'
    publishLocation: 'Container'